services:
  buergerforen:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elastic_buergerforen
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /media/singularity/Dokumente/Studentenfutter/CogntiveScience/MasterThesis/Code/master_thesis/elastic_persistent_dir/buergerforen:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  city_services:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elastic_city_services
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /media/singularity/Dokumente/Studentenfutter/CogntiveScience/MasterThesis/Code/master_thesis/elastic_persistent_dir/city_services:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge